runtime: nodejs18
instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: 'e87Y0=rbS3QE}tPZ'
  INSTANCE_CONNECTION_NAME: 'appsmith-403817:us-central1:appsmith'
  GCS_BUCKET_NAME: 'strapi-cms-gcp'
  GCS_BASE_PATH: 'cms'

beta_settings:
  cloud_sql_instances: 'appsmith-403817:us-central1:appsmith'