runtime: nodejs20
instance_class: F2

env_variables:
  HOST: '0.0.0.0'
  NODE_ENV: 'production'
  DATABASE_NAME: 'postgres'
  DATABASE_USER: 'postgres'
  DATABASE_PASSWORD: "`lxs2y^gSFY~^p1,"
  INSTANCE_CONNECTION_NAME: 'kevinblanco-appsmith:us-central1:strapi'
  GCS_BUCKET_NAME: 'strapi-kevin-cms-gcp'
  GCS_BASE_PATH: 'cms'

beta_settings:
  cloud_sql_instances: 'kevinblanco-appsmith:us-central1:strapi'